application: alantestdev
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
 
- url: /js
  static_dir: js
  
- url: /jscolor
  static_dir: jscolor
 
- url: /libjs
  static_dir: libjs
  
- url: /underscore_templates
  static_dir: underscore_templates
  
- url: /images
  static_dir: images
  
- url: /.*
  script: main.py
  